#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Loads the machines list
while read -r line
do
	key=`echo $line | awk '{print $1}'`
	val=`echo $line | awk '{print $2}'`

	NODES[$key]=$val
done < $CURRENT_DIR/../NODES

# Finally let's "bash" into the machine
machine_ip=${NODES[$1]}
ssh banketh@$machine_ip $2
