#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Load the machines list
while read -r line
do
	key=`echo $line | awk '{print $1}'`
	val=`echo $line | awk '{print $2}'`

	NODES[$key]=$val
done < $CURRENT_DIR/../NODES

IP="${NODES[$1]}"

ssh banketh@$IP tail -f /home/banketh/geth.log
