#!/bin/bash

################################################################################
#
#
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/_header

for i in `seq 0 3`;
do
	echo $i
	IP="${NODES[$i]}"
	curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":83}' $IP:21000
done 
