#!/bin/bash

################################################################################
#
#
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/_header

for i in `seq 0 6`;
do
	echo $i
	IP="${NODES[$i]}"
	ssh banketh@$IP tail /home/banketh/geth.log
done 
