#!/bin/bash

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo Resetting constellation on each server
for i in `seq 0 2`; do
	echo node-0$i
	$CURRENT_DIR/../../../04-mgmt/bash-node $i "ps aux | grep constellation | awk '{print \$2}' | xargs kill &>/dev/null"
	echo
done

echo
echo Launching constellation on each server
for i in `seq 0 2`; do
	echo node-0$i
	$CURRENT_DIR/../../../03-deploy/03-launch/constellation $i
	echo
done
