#!/bin/bash

# JP Morgan's Constellation (This one is _really_ long)
cd ~
git clone https://github.com/jpmorganchase/constellation.git
cd ~/constellation
stack setup
stack install
cp ~/.local/bin/* ~/execs/.
