#!/bin/bash

################################################################################
#
# Will upload geth from ./02-build/bin
#
# Usage
#
# ./03-deploy/02-upload/geth <node_number>
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/_header

DATE=`date -u +"%Y%m%d.%H%M%S"`
SSH_COMMAND="ssh -i $SSL_CERT_PATH $SSH_USERNAME@${NODES[$1]}"

echo Uploading new executable geth-$DATE

# Stop whatever geth process the machine is running
# This should be done with a management command (from 04-mgmt), but we want to make sure
$SSH_COMMAND "ps aux | grep geth | awk '{print \$2}' | xargs kill &>/dev/null"

$SSH_COMMAND "mkdir ~/execs &>/dev/null"
scp -i $SSL_CERT_PATH $CURRENT_DIR/../../02-build/bin/geth $SSH_USERNAME@${NODES[$1]}:~/execs/geth-$DATE

echo Creating Symlink
$SSH_COMMAND "ln -s -f ~/execs/geth-$DATE geth"

# Show result
$SSH_COMMAND "ls -al geth && ls -al ~/execs/geth-$DATE"
