#!/bin/bash

################################################################################
#
# Will launch constellation
#
# Usage
#
# ./03-deploy/03-launch/constellation <node_number>
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/_header

SSH_COMMAND="ssh -i $SSL_CERT_PATH $SSH_USERNAME@${NODES[$1]}"

# Launch constellation with nohup
$SSH_COMMAND << EOF
hostname
nohup \
	./constellation-node /home/$SSH_USERNAME/ethereum/constellation-conf \
	> /home/$SSH_USERNAME/constellation.log 2>&1 &
EOF

# Display information
$SSH_COMMAND "ps aux | grep constellation | grep -v grep"
$SSH_COMMAND "head /home/$SSH_USERNAME/constellation.log"
