#!/bin/bash

################################################################################
#
# Brief parameter explanation
#
# $1: Node number (as in node-00, node-01...)
# $2: Geth Parameters
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
SSH_USERNAME="$( cat deploy.conf | python -c "import json, sys;obj=json.load(sys.stdin);print obj[u'ssh-username']" )"
CLUSTER_NAME="$( cat deploy.conf | python -c "import json, sys;obj=json.load(sys.stdin);print obj[u'cluster-name']" )"

# Load the machines list
while read -r line
do
	key=`echo $line | awk '{print $1}'`
	val=`echo $line | awk '{print $2}'`

	NODES[$key]=$val
done < $CURRENT_DIR/../../01-servers/IPs/$CLUSTER_NAME-NODES

SSH_COMMAND="ssh $SSH_USERNAME@${NODES[$1]}"

# Just launch the node with the given parameters
echo $SSH_COMMAND << EOF
hostname

echo -e "\n======== Launch geth  ========\n" >> /home/banketh/geth.log

nohup \
	./geth --identity \$HOSTNAME \
		--datadir ~/ethereum ${@:2} \
	&>> /home/banketh/geth.log &
EOF

# Display information
echo $SSH_COMMAND "ps aux | grep geth | grep -v grep"
echo $SSH_COMMAND "tail -n30 /home/banketh/geth.log"

echo
echo We are done!
