#!/bin/bash

################################################################################
#
# This script will invoke the docker image
# infura/quorum-tools-suite
#
# You need to have docker installed in your machine!
#
# Usage:
#
# ./constellation <node_number>
#
# Output:
#
# Constellation public key
# Constellation private key
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/_header

# We create a temporary file we need to execute inside the container
echo "printf '\\n' | /execs/constellation-enclave-keygen /tmp/constellation-key &>/dev/null" > $ASSETS_DIR/$RND_NAME
echo "cp /tmp/constellation-key.pub $1-constellation-pub" >> $ASSETS_DIR/$RND_NAME
echo "cp /tmp/constellation-key.key $1-constellation-prv" >> $ASSETS_DIR/$RND_NAME
chmod +x $ASSETS_DIR/$RND_NAME

# Call the container
docker run -ti --rm -v $ASSETS_DIR:/workspace -w /workspace infura/quorum-tools-assets /bin/bash -c "/workspace/$RND_NAME"

# And delete the file
rm $ASSETS_DIR/$RND_NAME
