#!/bin/bash

################################################################################
#
# This script will invoke the docker image
# infura/quorum-tools-suite
#
# You need to have:
# * docker installed in your machine!
# * A genesis-source.json file in your assets directory (see genesis-source.sample)
#
# Usage:
#
# ./genesis
#
# Output:
#
# Dump of the genesis.json file
#
################################################################################

CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $CURRENT_DIR/_header

# We create a temporary file we need to execute inside the container
echo "cp /workspace/genesis-source.json /quorum-genesis/quorum-config.json" > $ASSETS_DIR/$RND_NAME
echo "cd /quorum-genesis && ./index.js && cat ./quorum-genesis.json" >> $ASSETS_DIR/$RND_NAME
echo "echo" >> $ASSETS_DIR/$RND_NAME
chmod +x $ASSETS_DIR/$RND_NAME

# Call the container
docker run -ti --rm -v $ASSETS_DIR:/workspace -w /workspace infura/quorum-tools-assets /bin/bash -c "/workspace/$RND_NAME"


# And delete the file
rm $ASSETS_DIR/$RND_NAME
