#!/bin/bash

## Voter accounts (5)
## <node number>_address_<account number inside node>
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/0_address_0
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/1_address_0
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/2_address_0
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/3_address_0
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/4_address_0

## Blockmaker accounts (3)
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/0_address_1
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/1_address_1
$CURRENT_DIR/../../02-deploy/01-prepare-assets/address > $ASSETS_DIR/2_address_1

echo Created voter and blockmaker ethereum accounts
find $CURRENT_DIR/../../02-deploy/00-assets -name "*_address_*"

## Nodekeys (7)
rm -rf $ASSETS_DIR/publickeys
for i in `seq 0 6`; do
	RESULT=$($CURRENT_DIR/../../02-deploy/01-prepare-assets/node)
	echo $RESULT | awk '{print $1;}' > $ASSETS_DIR/${i}_nodekey
	echo $RESULT | awk '{print $2;}' >> $ASSETS_DIR/publickeys
done

echo Created nodekeys and storing enodes for further configuration
find $CURRENT_DIR/../../02-deploy/00-assets -name "*_nodekey"
echo
cat $CURRENT_DIR/../../02-deploy/00-assets/publickeys

## Genesis File
## Write the genesis-specs.json file
GENESIS_SPECS=$CURRENT_DIR/../../02-deploy/00-assets/genesis-specs.json
VOTERS_ARRAY="\"0x$(get_address $ASSETS_DIR/0_address_0)\", "
VOTERS_ARRAY+="\"0x$(get_address $ASSETS_DIR/1_address_0)\","
VOTERS_ARRAY+="\"0x$(get_address $ASSETS_DIR/2_address_0)\","
VOTERS_ARRAY+="\"0x$(get_address $ASSETS_DIR/3_address_0)\","
VOTERS_ARRAY+="\"0x$(get_address $ASSETS_DIR/4_address_0)\""
MAKERS_ARRAY="\"0x$(get_address $ASSETS_DIR/0_address_1)\","
MAKERS_ARRAY+="\"0x$(get_address $ASSETS_DIR/1_address_1)\","
MAKERS_ARRAY+="\"0x$(get_address $ASSETS_DIR/2_address_1)\""
echo "{\"threshold\":3,\"voters\":[$VOTERS_ARRAY], \"makers\": [$MAKERS_ARRAY]}" | python -m"json.tool" > $GENESIS_SPECS

cat $GENESIS_SPECS

## Create and store the genesis block
GENESIS_FILE=$CURRENT_DIR/../../02-deploy/00-assets/genesis.json
$CURRENT_DIR/../../02-deploy/01-prepare-assets/genesis $GENESIS_SPECS > $GENESIS_FILE

echo Genesis file generated
head -n3 $GENESIS_FILE && echo "/.../" && tail -n3 $GENESIS_FILE
